spring.application.name=OSApiApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/lfr_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=laribas
spring.datasource.password=1diSenai
spring.jpa.show-sql=True
